name: release

permissions:
    contents: write

on:
    push:
        tags:
            - "v*"
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "8.0.x"

            - name: Publish win-x64
              run: |
                  dotnet restore LGSTrayUI/LGSTrayUI.csproj
                  dotnet publish LGSTrayUI/LGSTrayUI.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=none -p:EnableCompressionInSingleFile=true

            - name: Archive
              shell: pwsh
              run: |
                  $publish = "LGSTrayUI/bin/Release/net8.0-windows/win-x64/publish"
                  $zipPath = "DeviceBatteryTray-win-x64.zip"
                  Compress-Archive -Path "$publish/*" -DestinationPath $zipPath -Force
                  echo "ZIP_PATH=$zipPath" >> $env:GITHUB_ENV

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ${{ env.ZIP_PATH }}
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
